default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: geolocation_app_development

test:
  <<: *default
  database: geolocation_app_test

production:
  <<: *default
  database: geolocation_app_production
  username: geolocation_app
  password: <%= ENV['GELOCATION_APP_DATABASE_PASSWORD'] %>
